In [5]:
import pandas as pd

In [10]:
######################## PIVOT 1 ########################################

In [11]:
#Cap_Mensual_Oct#
df_pivot1_sep_Cap_Mensual_Oct = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Cap_Mensual_Oct')

In [12]:
df_pivot1_sep_Cap_Mensual_Oct.head()

,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas
0,Areli Paulina Carreón Rodríguez,Areli Paulina Carreón Rodríguez,PALAFOX HERNANDEZ LEONARI,NaN,CLAIMS,6 hrs,6
1,COSTA RICA ESPINDOLA RICARDO ESTEBAN,NaN,LECONA ALVAREZ CATALINA,Cdmx4@storecheck.com,FEMSA,6 hrs,6
2,ESPINOZA MARAVILLA PEDRO,NaN,QUITERIO GUZMAN ORLANDO,Cdmx33,FEMSA,6 hrs,6
3,HERNANDEZ HERNANDEZ PATRICIA,NaN,CORDOBA PACHECO ERNESTINA,CDMX26@storecheck.com,FEMSA,6 hrs,6
4,MARTINEZ VARGAS DANTE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,6 hrs,6

In [13]:
df_pivot1_sep_Cap_Mensual_Oct['Minutos'] = df_pivot1_sep_Cap_Mensual_Oct['Horas']*60
df_pivot1_sep_Cap_Mensual_Oct.head()

,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos
0,Areli Paulina Carreón Rodríguez,Areli Paulina Carreón Rodríguez,PALAFOX HERNANDEZ LEONARI,NaN,CLAIMS,6 hrs,6,360
1,COSTA RICA ESPINDOLA RICARDO ESTEBAN,NaN,LECONA ALVAREZ CATALINA,Cdmx4@storecheck.com,FEMSA,6 hrs,6,360
2,ESPINOZA MARAVILLA PEDRO,NaN,QUITERIO GUZMAN ORLANDO,Cdmx33,FEMSA,6 hrs,6,360
3,HERNANDEZ HERNANDEZ PATRICIA,NaN,CORDOBA PACHECO ERNESTINA,CDMX26@storecheck.com,FEMSA,6 hrs,6,360
4,MARTINEZ VARGAS DANTE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,6 hrs,6,360

In [14]:
df_pivot1_sep_Cap_Mensual_Oct['Selecciona tu nombre'].nunique()

123

In [15]:
df_pivot1_sep_Cap_Mensual_Oct['Tot_Minutos'] = df_pivot1_sep_Cap_Mensual_Oct['Minutos']*123
df_pivot1_sep_Cap_Mensual_Oct.head()

,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos,Tot_Minutos
0,Areli Paulina Carreón Rodríguez,Areli Paulina Carreón Rodríguez,PALAFOX HERNANDEZ LEONARI,NaN,CLAIMS,6 hrs,6,360,44280
1,COSTA RICA ESPINDOLA RICARDO ESTEBAN,NaN,LECONA ALVAREZ CATALINA,Cdmx4@storecheck.com,FEMSA,6 hrs,6,360,44280
2,ESPINOZA MARAVILLA PEDRO,NaN,QUITERIO GUZMAN ORLANDO,Cdmx33,FEMSA,6 hrs,6,360,44280
3,HERNANDEZ HERNANDEZ PATRICIA,NaN,CORDOBA PACHECO ERNESTINA,CDMX26@storecheck.com,FEMSA,6 hrs,6,360,44280
4,MARTINEZ VARGAS DANTE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,6 hrs,6,360,44280

In [20]:
#Refuerzo_Femsa#
df_pivot1_oct_Refuerzo_Femsa = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Refuerzo_Femsa')

In [21]:
df_pivot1_oct_Refuerzo_Femsa.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas
0,2021-10-05 09:41:13.423,CRUZ GARCIA SERGIO,NaN,CORDOBA PACHECO ERNESTINA,sanluisdelapaz@storecheck.com,FEMSA,2:30 hr.,2.3
1,2021-10-05 09:41:15.950,MARTINEZ VARGAS DANTE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3
2,2021-10-05 09:41:25.203,JULIAN HERNANDEZ PORFIRIO ADAN,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3
3,2021-10-05 09:41:25.394,MARTINEZ ZAMBRANO JUAN JOSE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3
4,2021-10-05 09:41:25.905,CONSTANTINO PULGARON OSVALDO,NaN,LECONA ALVAREZ CATALINA,8957,FEMSA,2:30 hr.,2.3

In [22]:
df_pivot1_oct_Refuerzo_Femsa['Selecciona tu nombre'].nunique()

67

In [23]:
df_pivot1_oct_Refuerzo_Femsa['Minutos'] = df_pivot1_oct_Refuerzo_Femsa['Horas']*60
df_pivot1_oct_Refuerzo_Femsa.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos
0,2021-10-05 09:41:13.423,CRUZ GARCIA SERGIO,NaN,CORDOBA PACHECO ERNESTINA,sanluisdelapaz@storecheck.com,FEMSA,2:30 hr.,2.3,138.0
1,2021-10-05 09:41:15.950,MARTINEZ VARGAS DANTE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3,138.0
2,2021-10-05 09:41:25.203,JULIAN HERNANDEZ PORFIRIO ADAN,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3,138.0
3,2021-10-05 09:41:25.394,MARTINEZ ZAMBRANO JUAN JOSE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3,138.0
4,2021-10-05 09:41:25.905,CONSTANTINO PULGARON OSVALDO,NaN,LECONA ALVAREZ CATALINA,8957,FEMSA,2:30 hr.,2.3,138.0

In [25]:
df_pivot1_oct_Refuerzo_Femsa['Tot_Minutos'] = df_pivot1_oct_Refuerzo_Femsa['Minutos']*67
df_pivot1_oct_Refuerzo_Femsa.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos,Tot_Minutos
0,2021-10-05 09:41:13.423,CRUZ GARCIA SERGIO,NaN,CORDOBA PACHECO ERNESTINA,sanluisdelapaz@storecheck.com,FEMSA,2:30 hr.,2.3,138.0,9246.0
1,2021-10-05 09:41:15.950,MARTINEZ VARGAS DANTE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3,138.0,9246.0
2,2021-10-05 09:41:25.203,JULIAN HERNANDEZ PORFIRIO ADAN,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3,138.0,9246.0
3,2021-10-05 09:41:25.394,MARTINEZ ZAMBRANO JUAN JOSE,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,2:30 hr.,2.3,138.0,9246.0
4,2021-10-05 09:41:25.905,CONSTANTINO PULGARON OSVALDO,NaN,LECONA ALVAREZ CATALINA,8957,FEMSA,2:30 hr.,2.3,138.0,9246.0

In [26]:
#Refuerzo_Arca#
df_pivot1_oct_Refuerzo_Arca = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Refuerzo_Arca')

In [27]:
df_pivot1_oct_Refuerzo_Arca.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas
0,2021-10-06 09:33:07.502,MARTINEZ SILVA JESUS ANGEL,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1
1,2021-10-06 09:33:10.252,VICENTE MATA KAREN GUADALUPE,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1
2,2021-10-06 09:33:12.185,GONZALEZ HERNANDEZ JUAN CARLOS,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1
3,2021-10-06 09:33:19.111,PALACIOS ROMERO SILVIA ELENA,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1
4,2021-10-06 09:33:23.519,ROBLEDO ARMENDARIZ MARIA DE LOS ANGELES,NaN,VAQUERO RAMIREZ VANESSA,aguascalientes3@storecheck,ARCA,2:10 hrs,2.1

In [28]:
df_pivot1_oct_Refuerzo_Arca['Selecciona tu nombre'].nunique()

19

In [29]:
df_pivot1_oct_Refuerzo_Arca['Minutos'] = df_pivot1_oct_Refuerzo_Arca['Horas']*60
df_pivot1_oct_Refuerzo_Arca.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos
0,2021-10-06 09:33:07.502,MARTINEZ SILVA JESUS ANGEL,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1,126.0
1,2021-10-06 09:33:10.252,VICENTE MATA KAREN GUADALUPE,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1,126.0
2,2021-10-06 09:33:12.185,GONZALEZ HERNANDEZ JUAN CARLOS,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1,126.0
3,2021-10-06 09:33:19.111,PALACIOS ROMERO SILVIA ELENA,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1,126.0
4,2021-10-06 09:33:23.519,ROBLEDO ARMENDARIZ MARIA DE LOS ANGELES,NaN,VAQUERO RAMIREZ VANESSA,aguascalientes3@storecheck,ARCA,2:10 hrs,2.1,126.0

In [30]:
df_pivot1_oct_Refuerzo_Arca['Tot_Minutos'] = df_pivot1_oct_Refuerzo_Arca['Minutos']*19
df_pivot1_oct_Refuerzo_Arca.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos,Tot_Minutos
0,2021-10-06 09:33:07.502,MARTINEZ SILVA JESUS ANGEL,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1,126.0,2394.0
1,2021-10-06 09:33:10.252,VICENTE MATA KAREN GUADALUPE,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1,126.0,2394.0
2,2021-10-06 09:33:12.185,GONZALEZ HERNANDEZ JUAN CARLOS,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1,126.0,2394.0
3,2021-10-06 09:33:19.111,PALACIOS ROMERO SILVIA ELENA,NaN,VAQUERO RAMIREZ VANESSA,NaN,ARCA,2:10 hrs,2.1,126.0,2394.0
4,2021-10-06 09:33:23.519,ROBLEDO ARMENDARIZ MARIA DE LOS ANGELES,NaN,VAQUERO RAMIREZ VANESSA,aguascalientes3@storecheck,ARCA,2:10 hrs,2.1,126.0,2394.0

In [31]:
#Refuerzo_Bep_Rica_Colim#
df_pivot1_oct_Refuerzo_Bep_Rica_Colim = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Refuerzo_Bep_Rica_Colim')

In [32]:
df_pivot1_oct_Refuerzo_Bep_Rica_Colim.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas
0,2021-10-07 09:26:48.120,BUENO ZAMORA JOSE ANTONIO,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,COLIMA,02:30:00,2.3
1,2021-10-07 09:26:51.170,NaN,Santiago Hernandez Claudia Jacqueline,KHALIL HERNANDEZ,jsantiago@storecheck.com,CDF,02:30:00,2.3
2,2021-10-07 09:27:03.531,NaN,CINTHIA ROSALIA CABALLERO POLANCO,KHALIL HERNANDEZ,NaN,BEPENSA,02:30:00,2.3
3,2021-10-07 09:27:08.332,CERVANTES CHAVARRIA MARTHA PATRICIA,NaN,CABALLERO POLANCO CINTHIA ROSALIA,NaN,BEPENSA,02:30:00,2.3
4,2021-10-07 09:27:10.144,BAUTISTA REYES CARLOS GUSTAVO,NaN,QUITERIO GUZMAN ORLANDO,tula2@storecheck.com,RICA,02:30:00,2.3

In [33]:
df_pivot1_oct_Refuerzo_Bep_Rica_Colim['Selecciona tu nombre'].nunique()

13

In [34]:
df_pivot1_oct_Refuerzo_Bep_Rica_Colim['Minutos'] = df_pivot1_oct_Refuerzo_Bep_Rica_Colim['Horas']*60
df_pivot1_oct_Refuerzo_Bep_Rica_Colim.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos
0,2021-10-07 09:26:48.120,BUENO ZAMORA JOSE ANTONIO,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,COLIMA,02:30:00,2.3,138.0
1,2021-10-07 09:26:51.170,NaN,Santiago Hernandez Claudia Jacqueline,KHALIL HERNANDEZ,jsantiago@storecheck.com,CDF,02:30:00,2.3,138.0
2,2021-10-07 09:27:03.531,NaN,CINTHIA ROSALIA CABALLERO POLANCO,KHALIL HERNANDEZ,NaN,BEPENSA,02:30:00,2.3,138.0
3,2021-10-07 09:27:08.332,CERVANTES CHAVARRIA MARTHA PATRICIA,NaN,CABALLERO POLANCO CINTHIA ROSALIA,NaN,BEPENSA,02:30:00,2.3,138.0
4,2021-10-07 09:27:10.144,BAUTISTA REYES CARLOS GUSTAVO,NaN,QUITERIO GUZMAN ORLANDO,tula2@storecheck.com,RICA,02:30:00,2.3,138.0

In [35]:
df_pivot1_oct_Refuerzo_Bep_Rica_Colim['Tot_Minutos'] = df_pivot1_oct_Refuerzo_Bep_Rica_Colim['Minutos']*13
df_pivot1_oct_Refuerzo_Bep_Rica_Colim.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos,Tot_Minutos
0,2021-10-07 09:26:48.120,BUENO ZAMORA JOSE ANTONIO,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,COLIMA,02:30:00,2.3,138.0,1794.0
1,2021-10-07 09:26:51.170,NaN,Santiago Hernandez Claudia Jacqueline,KHALIL HERNANDEZ,jsantiago@storecheck.com,CDF,02:30:00,2.3,138.0,1794.0
2,2021-10-07 09:27:03.531,NaN,CINTHIA ROSALIA CABALLERO POLANCO,KHALIL HERNANDEZ,NaN,BEPENSA,02:30:00,2.3,138.0,1794.0
3,2021-10-07 09:27:08.332,CERVANTES CHAVARRIA MARTHA PATRICIA,NaN,CABALLERO POLANCO CINTHIA ROSALIA,NaN,BEPENSA,02:30:00,2.3,138.0,1794.0
4,2021-10-07 09:27:10.144,BAUTISTA REYES CARLOS GUSTAVO,NaN,QUITERIO GUZMAN ORLANDO,tula2@storecheck.com,RICA,02:30:00,2.3,138.0,1794.0

In [41]:
#Refuerzo_CFD_Nog_Nayar#
df_pivot1_oct_Refuerzo_CDF_Nog_Nayar = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Refuerzo_CDF_Nog_Nayar')

In [42]:
df_pivot1_oct_Refuerzo_CDF_Nog_Nayar.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas
0,2021-10-08 10:04:09.000,HERNANDEZ PINTADO JUAN GADIEL,NaN,VAQUERO RAMIREZ VANESSA,NaN,NAYAR,2 hrs,2
1,2021-10-08 10:04:17.156,CELAYA BOJORQUEZ GISSEL,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,Ensenada@storecheck.com,CDF,2 hrs,2
2,2021-10-08 10:04:21.184,LOPEZ PEREZ SILVIA ARACELI,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,CDF,2 hrs,2
3,2021-10-08 10:04:24.419,PAEZ CERON MANUEL EULISES,NaN,KHALIL HERNANDEZ,NaN,CDF,2 hrs,2
4,2021-10-08 10:04:51.581,PANTOJA DELGADO SANDRA PATRICIA,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,CDF,2 hrs,2

In [43]:
df_pivot1_oct_Refuerzo_CDF_Nog_Nayar['Selecciona tu nombre'].nunique()

11

In [44]:
df_pivot1_oct_Refuerzo_CDF_Nog_Nayar['Minutos'] = df_pivot1_oct_Refuerzo_CDF_Nog_Nayar['Horas']*60
df_pivot1_oct_Refuerzo_CDF_Nog_Nayar.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos
0,2021-10-08 10:04:09.000,HERNANDEZ PINTADO JUAN GADIEL,NaN,VAQUERO RAMIREZ VANESSA,NaN,NAYAR,2 hrs,2,120
1,2021-10-08 10:04:17.156,CELAYA BOJORQUEZ GISSEL,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,Ensenada@storecheck.com,CDF,2 hrs,2,120
2,2021-10-08 10:04:21.184,LOPEZ PEREZ SILVIA ARACELI,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,CDF,2 hrs,2,120
3,2021-10-08 10:04:24.419,PAEZ CERON MANUEL EULISES,NaN,KHALIL HERNANDEZ,NaN,CDF,2 hrs,2,120
4,2021-10-08 10:04:51.581,PANTOJA DELGADO SANDRA PATRICIA,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,CDF,2 hrs,2,120

In [46]:
df_pivot1_oct_Refuerzo_CDF_Nog_Nayar['Tot_Minutos'] = df_pivot1_oct_Refuerzo_CDF_Nog_Nayar['Minutos']*11
df_pivot1_oct_Refuerzo_CDF_Nog_Nayar.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos,Tot_Minutos
0,2021-10-08 10:04:09.000,HERNANDEZ PINTADO JUAN GADIEL,NaN,VAQUERO RAMIREZ VANESSA,NaN,NAYAR,2 hrs,2,120,1320
1,2021-10-08 10:04:17.156,CELAYA BOJORQUEZ GISSEL,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,Ensenada@storecheck.com,CDF,2 hrs,2,120,1320
2,2021-10-08 10:04:21.184,LOPEZ PEREZ SILVIA ARACELI,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,CDF,2 hrs,2,120,1320
3,2021-10-08 10:04:24.419,PAEZ CERON MANUEL EULISES,NaN,KHALIL HERNANDEZ,NaN,CDF,2 hrs,2,120,1320
4,2021-10-08 10:04:51.581,PANTOJA DELGADO SANDRA PATRICIA,NaN,SANTIAGO HERNANDEZ CLAUDIA JACQUELINE,NaN,CDF,2 hrs,2,120,1320

In [48]:
#Curso_AS_Hlcs_rezagados#
df_pivot1_oct_CursoAS_Hlcs_Rezagados = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Curso_AS_Hlcs_rezagados')

In [49]:
df_pivot1_oct_CursoAS_Hlcs_Rezagados.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas
0,2021-10-15 15:29:03.440,ALEMAN CISNEROS MARIA GUADALUPE,NaN,VAQUERO RAMIREZ VANESSA,Monterrey@storecheck.com,ARCA,8 hrs,8
1,2021-10-15 15:29:08.779,SILVA LAZARO HEBERT LEONEL,NaN,CORDOBA PACHECO ERNESTINA,Morelia@storecheck.com,FEMSA,8 hrs,8
2,2021-10-15 15:29:14.295,PALACIOS ROMERO SILVIA ELENA,NaN,VAQUERO RAMIREZ VANESSA,chihuahua@storecheck.com,ARCA,8 hrs,8
3,2021-10-15 15:29:15.902,BAUTISTA REYES CARLOS GUSTAVO,NaN,QUITERIO GUZMAN ORLANDO,tula2@storecheck.com,RICA,8 hrs,8
4,2021-10-15 15:29:23.013,CERVANTES LOPEZ OSCAR,NaN,CORDOBA PACHECO ERNESTINA,Cdmx25,FEMSA,8 hrs,8

In [50]:
df_pivot1_oct_CursoAS_Hlcs_Rezagados['Selecciona tu nombre'].nunique()

20

In [51]:
df_pivot1_oct_CursoAS_Hlcs_Rezagados['Minutos'] = df_pivot1_oct_CursoAS_Hlcs_Rezagados['Horas']*60
df_pivot1_oct_CursoAS_Hlcs_Rezagados.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos
0,2021-10-15 15:29:03.440,ALEMAN CISNEROS MARIA GUADALUPE,NaN,VAQUERO RAMIREZ VANESSA,Monterrey@storecheck.com,ARCA,8 hrs,8,480
1,2021-10-15 15:29:08.779,SILVA LAZARO HEBERT LEONEL,NaN,CORDOBA PACHECO ERNESTINA,Morelia@storecheck.com,FEMSA,8 hrs,8,480
2,2021-10-15 15:29:14.295,PALACIOS ROMERO SILVIA ELENA,NaN,VAQUERO RAMIREZ VANESSA,chihuahua@storecheck.com,ARCA,8 hrs,8,480
3,2021-10-15 15:29:15.902,BAUTISTA REYES CARLOS GUSTAVO,NaN,QUITERIO GUZMAN ORLANDO,tula2@storecheck.com,RICA,8 hrs,8,480
4,2021-10-15 15:29:23.013,CERVANTES LOPEZ OSCAR,NaN,CORDOBA PACHECO ERNESTINA,Cdmx25,FEMSA,8 hrs,8,480

In [52]:
df_pivot1_oct_CursoAS_Hlcs_Rezagados['Tot_Minutos'] = df_pivot1_oct_CursoAS_Hlcs_Rezagados['Minutos']*20
df_pivot1_oct_CursoAS_Hlcs_Rezagados.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos,Tot_Minutos
0,2021-10-15 15:29:03.440,ALEMAN CISNEROS MARIA GUADALUPE,NaN,VAQUERO RAMIREZ VANESSA,Monterrey@storecheck.com,ARCA,8 hrs,8,480,9600
1,2021-10-15 15:29:08.779,SILVA LAZARO HEBERT LEONEL,NaN,CORDOBA PACHECO ERNESTINA,Morelia@storecheck.com,FEMSA,8 hrs,8,480,9600
2,2021-10-15 15:29:14.295,PALACIOS ROMERO SILVIA ELENA,NaN,VAQUERO RAMIREZ VANESSA,chihuahua@storecheck.com,ARCA,8 hrs,8,480,9600
3,2021-10-15 15:29:15.902,BAUTISTA REYES CARLOS GUSTAVO,NaN,QUITERIO GUZMAN ORLANDO,tula2@storecheck.com,RICA,8 hrs,8,480,9600
4,2021-10-15 15:29:23.013,CERVANTES LOPEZ OSCAR,NaN,CORDOBA PACHECO ERNESTINA,Cdmx25,FEMSA,8 hrs,8,480,9600

In [57]:
#Recertificacion#
df_pivot1_oct_Recertificacion = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Recertificacion ')

In [58]:
df_pivot1_oct_Recertificacion.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas
0,2021-10-08 08:24:02.291,NaN,María del socorro vargas gonzalez,VAQUERO RAMIREZ VANESSA,mexicali3@storecheck.com,ARCA,1 hrs,1
1,2021-10-08 08:24:31.478,JULIAN HERNANDEZ PORFIRIO ADAN,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,1 hrs,1
2,2021-10-08 08:24:42.339,NaN,Aaron natividad vargas,CABALLERO POLANCO CINTHIA ROSALIA,Xalapa3@storecheck.com,FEMSA,1 hrs,1
3,2021-10-08 08:24:44.152,FIERRO ROSAS JOSE SALVADOR,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,1 hrs,1
4,2021-10-08 08:24:45.586,SIERRA RESENDIZ GILBERTO,NaN,CORDOBA PACHECO ERNESTINA,celaya@storecheck.com,FEMSA,1 hrs,1

In [59]:
df_pivot1_oct_Recertificacion['Selecciona tu nombre'].nunique()

12

In [60]:
df_pivot1_oct_Recertificacion['Minutos'] = df_pivot1_oct_Recertificacion['Horas']*60
df_pivot1_oct_Recertificacion.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos
0,2021-10-08 08:24:02.291,NaN,María del socorro vargas gonzalez,VAQUERO RAMIREZ VANESSA,mexicali3@storecheck.com,ARCA,1 hrs,1,60
1,2021-10-08 08:24:31.478,JULIAN HERNANDEZ PORFIRIO ADAN,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,1 hrs,1,60
2,2021-10-08 08:24:42.339,NaN,Aaron natividad vargas,CABALLERO POLANCO CINTHIA ROSALIA,Xalapa3@storecheck.com,FEMSA,1 hrs,1,60
3,2021-10-08 08:24:44.152,FIERRO ROSAS JOSE SALVADOR,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,1 hrs,1,60
4,2021-10-08 08:24:45.586,SIERRA RESENDIZ GILBERTO,NaN,CORDOBA PACHECO ERNESTINA,celaya@storecheck.com,FEMSA,1 hrs,1,60

In [61]:
df_pivot1_oct_Recertificacion['Tot_Minutos'] = df_pivot1_oct_Recertificacion['Minutos']*12
df_pivot1_oct_Recertificacion.head()

,Marca temporal,Selecciona tu nombre,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas,Minutos,Tot_Minutos
0,2021-10-08 08:24:02.291,NaN,María del socorro vargas gonzalez,VAQUERO RAMIREZ VANESSA,mexicali3@storecheck.com,ARCA,1 hrs,1,60,720
1,2021-10-08 08:24:31.478,JULIAN HERNANDEZ PORFIRIO ADAN,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,1 hrs,1,60,720
2,2021-10-08 08:24:42.339,NaN,Aaron natividad vargas,CABALLERO POLANCO CINTHIA ROSALIA,Xalapa3@storecheck.com,FEMSA,1 hrs,1,60,720
3,2021-10-08 08:24:44.152,FIERRO ROSAS JOSE SALVADOR,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,1 hrs,1,60,720
4,2021-10-08 08:24:45.586,SIERRA RESENDIZ GILBERTO,NaN,CORDOBA PACHECO ERNESTINA,celaya@storecheck.com,FEMSA,1 hrs,1,60,720

In [1]:
######################## PIVOT 2 ########################################

In [6]:
import numpy as np

In [3]:
# CAP General

In [7]:
df_pivot2 = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Pivot2')

In [8]:
df_pivot1_oct_Cap_Mensual_Oct = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Cap_Mensual_Oct')

In [9]:
df_pivot1_oct_Cap_Mensual_Oct.rename(columns={"Selecciona tu nombre": "Nombre_Completo"}, inplace=True)

In [10]:
df_cross_Cap_mens_oct = df_pivot2.merge(df_pivot1_oct_Cap_Mensual_Oct, on='Nombre_Completo', how='right')

In [11]:
df_cross_Cap_mens_oct

,Nombre_Completo,fecha_AsistEval_CAPGral,fecha_AsistEval_EVAGral,fecha_Asistencia_RefFEMSA,fecha_Asistencia_RefARCA,fecha_Asistencia_Ref_BepRicaCol,fecha_Asistencia_Ref_CDFNogNayar,fecha_Asistencia_Recertificacion,fecha_Calif_Recertificacion,fecha_Asistencia_CursoAS_Hlcs_Rezagados,Suma_Refuerzos,Si no esta tu nombre ingresalo en esta sección (Nombre completo empezando por apellidos),Líder/Regional,Usuario (En caso de NO tener colocar NA ),ESTUDIO QUE EVALÚAS,Tiempo/duracion,Horas
0,Areli Paulina Carreón Rodríguez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Areli Paulina Carreón Rodríguez,PALAFOX HERNANDEZ LEONARI,NaN,CLAIMS,6 hrs,6
1,COSTA RICA ESPINDOLA RICARDO ESTEBAN,1.0,0.888889,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,LECONA ALVAREZ CATALINA,Cdmx4@storecheck.com,FEMSA,6 hrs,6
2,ESPINOZA MARAVILLA PEDRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QUITERIO GUZMAN ORLANDO,Cdmx33,FEMSA,6 hrs,6
3,HERNANDEZ HERNANDEZ PATRICIA,1.0,1.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,CORDOBA PACHECO ERNESTINA,CDMX26@storecheck.com,FEMSA,6 hrs,6
4,MARTINEZ VARGAS DANTE,1.0,0.944444,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,6 hrs,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,SANCHEZ GOMEZ MARIA EVA,NaN,0.777778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CORDOBA PACHECO ERNESTINA,leon5@storeck.com,FEMSA,6 hrs,6
124,ZUÑIGA LEMUS EDUARDO,1.0,0.833333,NaN,NaN,NaN,NaN,0.733333,NaN,1.0,1.0,NaN,LECONA ALVAREZ CATALINA,36,FEMSA,6 hrs,6
125,ALEJANDRO PABLO MARIA ARACELI,1.0,1.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,QUITERIO GUZMAN ORLANDO,NaN,FEMSA,6 hrs,6
126,PEREZ VENTURA OSCAR,1.0,0.888889,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,CORDOBA PACHECO ERNESTINA,NaN,FEMSA,6 hrs,6
127,RUIZ GARCIA MAURICIO,1.0,1.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,CORDOBA PACHECO ERNESTINA,NaN,FEMSA,6 hrs,6

In [12]:
df_cross_Cap_mens_oct['fecha_AsistEval_CAPGral_2']=1

In [13]:
df_cap_oct=df_cross_Cap_mens_oct[['Nombre_Completo', 'fecha_AsistEval_CAPGral_2']]

In [14]:
df_cap_oct

                          Nombre_Completo  fecha_AsistEval_CAPGral_2
0        Areli Paulina Carreón Rodríguez                           1
1    COSTA RICA ESPINDOLA RICARDO ESTEBAN                          1
2                ESPINOZA MARAVILLA PEDRO                          1
3            HERNANDEZ HERNANDEZ PATRICIA                          1
4                   MARTINEZ VARGAS DANTE                          1
..                                    ...                        ...
123               SANCHEZ GOMEZ MARIA EVA                          1
124                  ZUÑIGA LEMUS EDUARDO                          1
125         ALEJANDRO PABLO MARIA ARACELI                          1
126                   PEREZ VENTURA OSCAR                          1
127                  RUIZ GARCIA MAURICIO                          1

[128 rows x 2 columns]

In [15]:
df_cap_oct['Nombre_Completo'].nunique()

124

In [16]:
df_cap_oct=df_cap_oct.drop_duplicates(subset=['Nombre_Completo'])

In [17]:
df_pivot2.insert(1, 'fecha_AsistEval_CAPGral_2', df_pivot2['Nombre_Completo'].map(df_cap_oct.set_index('Nombre_Completo')['fecha_AsistEval_CAPGral_2']))
print (df_pivot2)

                        Nombre_Completo  fecha_AsistEval_CAPGral_2  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL                        NaN
1      AGUIAR SANCHEZ DOLORES MARGARITA                        NaN
2         ALEJANDRO PABLO MARIA ARACELI                        1.0
3       ALEMAN CISNEROS MARIA GUADALUPE                        NaN
4            ALMARAZ RUIZ CLAUDIA IVONE                        NaN
..                                  ...                        ...
270             GISELA URBALEJO SANCHEZ                        1.0
271                   Natividad vargas                         NaN
272         JINEZ CÁRDENAS ROSA CECILIA                        NaN
273       Cesar guadalupe moreno robles                        1.0
274  Carlos Alberto González Rodríguez                         NaN

     fecha_AsistEval_CAPGral  fecha_AsistEval_EVAGral  \
0                        NaN                      NaN
1                        NaN                      NaN
2                        1.0                 1.000000
3                        NaN                 0.944444
4                        NaN                      NaN
..                       ...                      ...
270                      1.0                 0.888889
271                      NaN                      NaN
272                      NaN                      NaN
273                      NaN                 0.944444
274                      NaN                 0.833333

     fecha_Asistencia_RefFEMSA  fecha_Asistencia_RefARCA  \
0                          NaN                       NaN
1                          NaN                       NaN
2                          1.0                       NaN
3                          NaN                       NaN
4                          NaN                       NaN
..                         ...                       ...
270                        NaN                       NaN
271                        NaN                       NaN
272                        NaN                       NaN
273                        NaN                       1.0
274                        NaN                       NaN

     fecha_Asistencia_Ref_BepRicaCol  fecha_Asistencia_Ref_CDFNogNayar  \
0                                NaN                               NaN
1                                NaN                               NaN
2                                NaN                               NaN
3                                NaN                               NaN
4                                NaN                               NaN
..                               ...                               ...
270                              NaN                               1.0
271                              NaN                               NaN
272                              NaN                               NaN
273                              NaN                               NaN
274                              NaN                               NaN

     fecha_Asistencia_Recertificacion  fecha_Calif_Recertificacion  \
0                                 NaN                          NaN
1                                 NaN                          NaN
2                                 NaN                          NaN
3                                 NaN                          NaN
4                                 NaN                          NaN
..                                ...                          ...
270                               NaN                          NaN
271                               NaN                          NaN
272                               NaN                          NaN
273                               NaN                          NaN
274                               NaN                          NaN

     fecha_Asistencia_CursoAS_Hlcs_Rezagados  Suma_Refuerzos
0                                        NaN               0
1                                        NaN               0
2                                        NaN               1
3                                        NaN               0
4                                        NaN               0
..                                       ...             ...
270                                      NaN               1
271                                      NaN               0
272                                      NaN               0
273                                      NaN               1
274                                      NaN               0

[275 rows x 12 columns]

In [18]:
# EVA General

In [19]:
Eval_oct21 = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Hoja1')

In [20]:
df_evals_oct=Eval_oct21[['NOMBRE COMPLETO', 'Calificacion']]

In [21]:
df_evals_oct

                      NOMBRE COMPLETO  Calificacion
0            Adeida santiago santiago          1.00
1       ALEJANDRO PABLO MARIA ARACELI          1.00
2              Ana Bertha Cruz Olvera          0.90
3         ARANO MOLINA JULIO BALTAZAR          1.00
4     Areli Paulina Carreón Rodríguez          0.85
..                                ...           ...
129            VAZQUEZ FERRA PATRICIA          1.00
130             VEGA JOAQUIN FERNANDO          1.00
131  VELASQUEZ CERON DIANA JACQUELINE          1.00
132      VICENTE MATA KAREN GUADALUPE          0.95
133              ZUÑIGA LEMUS EDUARDO          1.00

[134 rows x 2 columns]

In [22]:
df_evals_oct.rename(columns={"NOMBRE COMPLETO": "Nombre_Completo"}, inplace=True)

In [23]:
df_evals_oct.rename(columns={"Calificacion ": "Calificacion2"}, inplace=True)

In [24]:
df_evals_oct=df_evals_oct.drop_duplicates(subset=['Nombre_Completo'])

In [25]:
df_pivot2.insert(1, 'Calificacion', df_pivot2['Nombre_Completo'].map(df_evals_oct.set_index('Nombre_Completo')['Calificacion']))
print (df_pivot2)

                        Nombre_Completo  Calificacion  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL           NaN
1      AGUIAR SANCHEZ DOLORES MARGARITA           NaN
2         ALEJANDRO PABLO MARIA ARACELI           1.0
3       ALEMAN CISNEROS MARIA GUADALUPE           NaN
4            ALMARAZ RUIZ CLAUDIA IVONE           NaN
..                                  ...           ...
270             GISELA URBALEJO SANCHEZ           1.0
271                   Natividad vargas            NaN
272         JINEZ CÁRDENAS ROSA CECILIA           NaN
273       Cesar guadalupe moreno robles           NaN
274  Carlos Alberto González Rodríguez            NaN

     fecha_AsistEval_CAPGral_2  fecha_AsistEval_CAPGral  \
0                          NaN                      NaN
1                          NaN                      NaN
2                          1.0                      1.0
3                          NaN                      NaN
4                          NaN                      NaN
..                         ...                      ...
270                        1.0                      1.0
271                        NaN                      NaN
272                        NaN                      NaN
273                        1.0                      NaN
274                        NaN                      NaN

     fecha_AsistEval_EVAGral  fecha_Asistencia_RefFEMSA  \
0                        NaN                        NaN
1                        NaN                        NaN
2                   1.000000                        1.0
3                   0.944444                        NaN
4                        NaN                        NaN
..                       ...                        ...
270                 0.888889                        NaN
271                      NaN                        NaN
272                      NaN                        NaN
273                 0.944444                        NaN
274                 0.833333                        NaN

     fecha_Asistencia_RefARCA  fecha_Asistencia_Ref_BepRicaCol  \
0                         NaN                              NaN
1                         NaN                              NaN
2                         NaN                              NaN
3                         NaN                              NaN
4                         NaN                              NaN
..                        ...                              ...
270                       NaN                              NaN
271                       NaN                              NaN
272                       NaN                              NaN
273                       1.0                              NaN
274                       NaN                              NaN

     fecha_Asistencia_Ref_CDFNogNayar  fecha_Asistencia_Recertificacion  \
0                                 NaN                               NaN
1                                 NaN                               NaN
2                                 NaN                               NaN
3                                 NaN                               NaN
4                                 NaN                               NaN
..                                ...                               ...
270                               1.0                               NaN
271                               NaN                               NaN
272                               NaN                               NaN
273                               NaN                               NaN
274                               NaN                               NaN

     fecha_Calif_Recertificacion  fecha_Asistencia_CursoAS_Hlcs_Rezagados  \
0                            NaN                                      NaN
1                            NaN                                      NaN
2                            NaN                                      NaN
3                            NaN                                      NaN
4                            NaN                                      NaN
..                           ...                                      ...
270                          NaN                                      NaN
271                          NaN                                      NaN
272                          NaN                                      NaN
273                          NaN                                      NaN
274                          NaN                                      NaN

     Suma_Refuerzos
0                 0
1                 0
2                 1
3                 0
4                 0
..              ...
270               1
271               0
272               0
273               1
274               0

[275 rows x 13 columns]

In [26]:
# refuerzo Femsa

In [27]:
Refuerzo_Femsa = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Refuerzo_Femsa')

In [28]:
Refuerzo_Femsa['fecha_Asistencia_RefFEMSA2']=1

In [29]:
Refuerzo_Femsa=Refuerzo_Femsa[['Selecciona tu nombre', 'fecha_Asistencia_RefFEMSA2']]

In [30]:
Refuerzo_Femsa.rename(columns={"Selecciona tu nombre": "Nombre_Completo"}, inplace=True)

In [31]:
Refuerzo_Femsa=Refuerzo_Femsa.drop_duplicates(subset=['Nombre_Completo'])

In [32]:
df_pivot2.insert(1, 'fecha_Asistencia_RefFEMSA2', df_pivot2['Nombre_Completo'].map(Refuerzo_Femsa.set_index('Nombre_Completo')['fecha_Asistencia_RefFEMSA2']))
print (df_pivot2)

                        Nombre_Completo  fecha_Asistencia_RefFEMSA2  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL                         NaN
1      AGUIAR SANCHEZ DOLORES MARGARITA                         NaN
2         ALEJANDRO PABLO MARIA ARACELI                         1.0
3       ALEMAN CISNEROS MARIA GUADALUPE                         NaN
4            ALMARAZ RUIZ CLAUDIA IVONE                         NaN
..                                  ...                         ...
270             GISELA URBALEJO SANCHEZ                         NaN
271                   Natividad vargas                          NaN
272         JINEZ CÁRDENAS ROSA CECILIA                         NaN
273       Cesar guadalupe moreno robles                         NaN
274  Carlos Alberto González Rodríguez                          NaN

     Calificacion  fecha_AsistEval_CAPGral_2  fecha_AsistEval_CAPGral  \
0             NaN                        NaN                      NaN
1             NaN                        NaN                      NaN
2             1.0                        1.0                      1.0
3             NaN                        NaN                      NaN
4             NaN                        NaN                      NaN
..            ...                        ...                      ...
270           1.0                        1.0                      1.0
271           NaN                        NaN                      NaN
272           NaN                        NaN                      NaN
273           NaN                        1.0                      NaN
274           NaN                        NaN                      NaN

     fecha_AsistEval_EVAGral  fecha_Asistencia_RefFEMSA  \
0                        NaN                        NaN
1                        NaN                        NaN
2                   1.000000                        1.0
3                   0.944444                        NaN
4                        NaN                        NaN
..                       ...                        ...
270                 0.888889                        NaN
271                      NaN                        NaN
272                      NaN                        NaN
273                 0.944444                        NaN
274                 0.833333                        NaN

     fecha_Asistencia_RefARCA  fecha_Asistencia_Ref_BepRicaCol  \
0                         NaN                              NaN
1                         NaN                              NaN
2                         NaN                              NaN
3                         NaN                              NaN
4                         NaN                              NaN
..                        ...                              ...
270                       NaN                              NaN
271                       NaN                              NaN
272                       NaN                              NaN
273                       1.0                              NaN
274                       NaN                              NaN

     fecha_Asistencia_Ref_CDFNogNayar  fecha_Asistencia_Recertificacion  \
0                                 NaN                               NaN
1                                 NaN                               NaN
2                                 NaN                               NaN
3                                 NaN                               NaN
4                                 NaN                               NaN
..                                ...                               ...
270                               1.0                               NaN
271                               NaN                               NaN
272                               NaN                               NaN
273                               NaN                               NaN
274                               NaN                               NaN

     fecha_Calif_Recertificacion  fecha_Asistencia_CursoAS_Hlcs_Rezagados  \
0                            NaN                                      NaN
1                            NaN                                      NaN
2                            NaN                                      NaN
3                            NaN                                      NaN
4                            NaN                                      NaN
..                           ...                                      ...
270                          NaN                                      NaN
271                          NaN                                      NaN
272                          NaN                                      NaN
273                          NaN                                      NaN
274                          NaN                                      NaN

     Suma_Refuerzos
0                 0
1                 0
2                 1
3                 0
4                 0
..              ...
270               1
271               0
272               0
273               1
274               0

[275 rows x 14 columns]

In [33]:
# refuerzo Arca

In [34]:
Refuerzo_Arca = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Refuerzo_Arca')

In [35]:
Refuerzo_Arca['fecha_Asistencia_RefARCA2']=1

In [36]:
Refuerzo_Arca=Refuerzo_Arca[['Selecciona tu nombre', 'fecha_Asistencia_RefARCA2']]

In [37]:
Refuerzo_Arca.rename(columns={"Selecciona tu nombre": "Nombre_Completo"}, inplace=True)

In [38]:
Refuerzo_Arca=Refuerzo_Arca.drop_duplicates(subset=['Nombre_Completo'])

In [39]:
df_pivot2.insert(1, 'fecha_Asistencia_RefARCA2', df_pivot2['Nombre_Completo'].map(Refuerzo_Arca.set_index('Nombre_Completo')['fecha_Asistencia_RefARCA2']))
print (df_pivot2)

                        Nombre_Completo  fecha_Asistencia_RefARCA2  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL                        NaN
1      AGUIAR SANCHEZ DOLORES MARGARITA                        NaN
2         ALEJANDRO PABLO MARIA ARACELI                        NaN
3       ALEMAN CISNEROS MARIA GUADALUPE                        1.0
4            ALMARAZ RUIZ CLAUDIA IVONE                        NaN
..                                  ...                        ...
270             GISELA URBALEJO SANCHEZ                        NaN
271                   Natividad vargas                         NaN
272         JINEZ CÁRDENAS ROSA CECILIA                        NaN
273       Cesar guadalupe moreno robles                        1.0
274  Carlos Alberto González Rodríguez                         NaN

     fecha_Asistencia_RefFEMSA2  Calificacion  fecha_AsistEval_CAPGral_2  \
0                           NaN           NaN                        NaN
1                           NaN           NaN                        NaN
2                           1.0           1.0                        1.0
3                           NaN           NaN                        NaN
4                           NaN           NaN                        NaN
..                          ...           ...                        ...
270                         NaN           1.0                        1.0
271                         NaN           NaN                        NaN
272                         NaN           NaN                        NaN
273                         NaN           NaN                        1.0
274                         NaN           NaN                        NaN

     fecha_AsistEval_CAPGral  fecha_AsistEval_EVAGral  \
0                        NaN                      NaN
1                        NaN                      NaN
2                        1.0                 1.000000
3                        NaN                 0.944444
4                        NaN                      NaN
..                       ...                      ...
270                      1.0                 0.888889
271                      NaN                      NaN
272                      NaN                      NaN
273                      NaN                 0.944444
274                      NaN                 0.833333

     fecha_Asistencia_RefFEMSA  fecha_Asistencia_RefARCA  \
0                          NaN                       NaN
1                          NaN                       NaN
2                          1.0                       NaN
3                          NaN                       NaN
4                          NaN                       NaN
..                         ...                       ...
270                        NaN                       NaN
271                        NaN                       NaN
272                        NaN                       NaN
273                        NaN                       1.0
274                        NaN                       NaN

     fecha_Asistencia_Ref_BepRicaCol  fecha_Asistencia_Ref_CDFNogNayar  \
0                                NaN                               NaN
1                                NaN                               NaN
2                                NaN                               NaN
3                                NaN                               NaN
4                                NaN                               NaN
..                               ...                               ...
270                              NaN                               1.0
271                              NaN                               NaN
272                              NaN                               NaN
273                              NaN                               NaN
274                              NaN                               NaN

     fecha_Asistencia_Recertificacion  fecha_Calif_Recertificacion  \
0                                 NaN                          NaN
1                                 NaN                          NaN
2                                 NaN                          NaN
3                                 NaN                          NaN
4                                 NaN                          NaN
..                                ...                          ...
270                               NaN                          NaN
271                               NaN                          NaN
272                               NaN                          NaN
273                               NaN                          NaN
274                               NaN                          NaN

     fecha_Asistencia_CursoAS_Hlcs_Rezagados  Suma_Refuerzos
0                                        NaN               0
1                                        NaN               0
2                                        NaN               1
3                                        NaN               0
4                                        NaN               0
..                                       ...             ...
270                                      NaN               1
271                                      NaN               0
272                                      NaN               0
273                                      NaN               1
274                                      NaN               0

[275 rows x 15 columns]

In [40]:
# Refuerzo_Bep_Rica_Colim

In [41]:
Refuerzo_Bep_Rica_Colim = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Refuerzo_Bep_Rica_Colim')

In [42]:
Refuerzo_Bep_Rica_Colim['fecha_Asistencia_Ref_BepRicaCol2']=1

In [43]:
Refuerzo_Bep_Rica_Colim=Refuerzo_Bep_Rica_Colim[['Selecciona tu nombre', 'fecha_Asistencia_Ref_BepRicaCol2']]

In [44]:
Refuerzo_Bep_Rica_Colim.rename(columns={"Selecciona tu nombre": "Nombre_Completo"}, inplace=True)

In [45]:
Refuerzo_Bep_Rica_Colim=Refuerzo_Bep_Rica_Colim.drop_duplicates(subset=['Nombre_Completo'])

In [46]:
df_pivot2.insert(1, 'fecha_Asistencia_Ref_BepRicaCol2', df_pivot2['Nombre_Completo'].map(Refuerzo_Bep_Rica_Colim.set_index('Nombre_Completo')['fecha_Asistencia_Ref_BepRicaCol2']))
print (df_pivot2)

                        Nombre_Completo  fecha_Asistencia_Ref_BepRicaCol2  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL                               NaN
1      AGUIAR SANCHEZ DOLORES MARGARITA                               NaN
2         ALEJANDRO PABLO MARIA ARACELI                               NaN
3       ALEMAN CISNEROS MARIA GUADALUPE                               NaN
4            ALMARAZ RUIZ CLAUDIA IVONE                               NaN
..                                  ...                               ...
270             GISELA URBALEJO SANCHEZ                               NaN
271                   Natividad vargas                                NaN
272         JINEZ CÁRDENAS ROSA CECILIA                               NaN
273       Cesar guadalupe moreno robles                               NaN
274  Carlos Alberto González Rodríguez                                NaN

     fecha_Asistencia_RefARCA2  fecha_Asistencia_RefFEMSA2  Calificacion  \
0                          NaN                         NaN           NaN
1                          NaN                         NaN           NaN
2                          NaN                         1.0           1.0
3                          1.0                         NaN           NaN
4                          NaN                         NaN           NaN
..                         ...                         ...           ...
270                        NaN                         NaN           1.0
271                        NaN                         NaN           NaN
272                        NaN                         NaN           NaN
273                        1.0                         NaN           NaN
274                        NaN                         NaN           NaN

     fecha_AsistEval_CAPGral_2  fecha_AsistEval_CAPGral  \
0                          NaN                      NaN
1                          NaN                      NaN
2                          1.0                      1.0
3                          NaN                      NaN
4                          NaN                      NaN
..                         ...                      ...
270                        1.0                      1.0
271                        NaN                      NaN
272                        NaN                      NaN
273                        1.0                      NaN
274                        NaN                      NaN

     fecha_AsistEval_EVAGral  fecha_Asistencia_RefFEMSA  \
0                        NaN                        NaN
1                        NaN                        NaN
2                   1.000000                        1.0
3                   0.944444                        NaN
4                        NaN                        NaN
..                       ...                        ...
270                 0.888889                        NaN
271                      NaN                        NaN
272                      NaN                        NaN
273                 0.944444                        NaN
274                 0.833333                        NaN

     fecha_Asistencia_RefARCA  fecha_Asistencia_Ref_BepRicaCol  \
0                         NaN                              NaN
1                         NaN                              NaN
2                         NaN                              NaN
3                         NaN                              NaN
4                         NaN                              NaN
..                        ...                              ...
270                       NaN                              NaN
271                       NaN                              NaN
272                       NaN                              NaN
273                       1.0                              NaN
274                       NaN                              NaN

     fecha_Asistencia_Ref_CDFNogNayar  fecha_Asistencia_Recertificacion  \
0                                 NaN                               NaN
1                                 NaN                               NaN
2                                 NaN                               NaN
3                                 NaN                               NaN
4                                 NaN                               NaN
..                                ...                               ...
270                               1.0                               NaN
271                               NaN                               NaN
272                               NaN                               NaN
273                               NaN                               NaN
274                               NaN                               NaN

     fecha_Calif_Recertificacion  fecha_Asistencia_CursoAS_Hlcs_Rezagados  \
0                            NaN                                      NaN
1                            NaN                                      NaN
2                            NaN                                      NaN
3                            NaN                                      NaN
4                            NaN                                      NaN
..                           ...                                      ...
270                          NaN                                      NaN
271                          NaN                                      NaN
272                          NaN                                      NaN
273                          NaN                                      NaN
274                          NaN                                      NaN

     Suma_Refuerzos
0                 0
1                 0
2                 1
3                 0
4                 0
..              ...
270               1
271               0
272               0
273               1
274               0

[275 rows x 16 columns]

In [47]:
# Refuerzo_CFD_Nog_Nayar

In [48]:
Refuerzo_CFD_Nog_Nayar = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Refuerzo_CDF_Nog_Nayar')

In [49]:
Refuerzo_CFD_Nog_Nayar['fecha_Asistencia_Ref_CDFNogNayar2']=1

In [50]:
Refuerzo_CFD_Nog_Nayar=Refuerzo_CFD_Nog_Nayar[['Selecciona tu nombre', 'fecha_Asistencia_Ref_CDFNogNayar2']]

In [51]:
Refuerzo_CFD_Nog_Nayar.rename(columns={"Selecciona tu nombre": "Nombre_Completo"}, inplace=True)

In [52]:
Refuerzo_CFD_Nog_Nayar=Refuerzo_CFD_Nog_Nayar.drop_duplicates(subset=['Nombre_Completo'])

In [53]:
df_pivot2.insert(1, 'fecha_Asistencia_Ref_CDFNogNayar2', df_pivot2['Nombre_Completo'].map(Refuerzo_CFD_Nog_Nayar.set_index('Nombre_Completo')['fecha_Asistencia_Ref_CDFNogNayar2']))
print (df_pivot2)

                        Nombre_Completo  fecha_Asistencia_Ref_CDFNogNayar2  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL                                NaN
1      AGUIAR SANCHEZ DOLORES MARGARITA                                NaN
2         ALEJANDRO PABLO MARIA ARACELI                                NaN
3       ALEMAN CISNEROS MARIA GUADALUPE                                NaN
4            ALMARAZ RUIZ CLAUDIA IVONE                                NaN
..                                  ...                                ...
270             GISELA URBALEJO SANCHEZ                                NaN
271                   Natividad vargas                                 NaN
272         JINEZ CÁRDENAS ROSA CECILIA                                NaN
273       Cesar guadalupe moreno robles                                NaN
274  Carlos Alberto González Rodríguez                                 NaN

     fecha_Asistencia_Ref_BepRicaCol2  fecha_Asistencia_RefARCA2  \
0                                 NaN                        NaN
1                                 NaN                        NaN
2                                 NaN                        NaN
3                                 NaN                        1.0
4                                 NaN                        NaN
..                                ...                        ...
270                               NaN                        NaN
271                               NaN                        NaN
272                               NaN                        NaN
273                               NaN                        1.0
274                               NaN                        NaN

     fecha_Asistencia_RefFEMSA2  Calificacion  fecha_AsistEval_CAPGral_2  \
0                           NaN           NaN                        NaN
1                           NaN           NaN                        NaN
2                           1.0           1.0                        1.0
3                           NaN           NaN                        NaN
4                           NaN           NaN                        NaN
..                          ...           ...                        ...
270                         NaN           1.0                        1.0
271                         NaN           NaN                        NaN
272                         NaN           NaN                        NaN
273                         NaN           NaN                        1.0
274                         NaN           NaN                        NaN

     fecha_AsistEval_CAPGral  fecha_AsistEval_EVAGral  \
0                        NaN                      NaN
1                        NaN                      NaN
2                        1.0                 1.000000
3                        NaN                 0.944444
4                        NaN                      NaN
..                       ...                      ...
270                      1.0                 0.888889
271                      NaN                      NaN
272                      NaN                      NaN
273                      NaN                 0.944444
274                      NaN                 0.833333

     fecha_Asistencia_RefFEMSA  fecha_Asistencia_RefARCA  \
0                          NaN                       NaN
1                          NaN                       NaN
2                          1.0                       NaN
3                          NaN                       NaN
4                          NaN                       NaN
..                         ...                       ...
270                        NaN                       NaN
271                        NaN                       NaN
272                        NaN                       NaN
273                        NaN                       1.0
274                        NaN                       NaN

     fecha_Asistencia_Ref_BepRicaCol  fecha_Asistencia_Ref_CDFNogNayar  \
0                                NaN                               NaN
1                                NaN                               NaN
2                                NaN                               NaN
3                                NaN                               NaN
4                                NaN                               NaN
..                               ...                               ...
270                              NaN                               1.0
271                              NaN                               NaN
272                              NaN                               NaN
273                              NaN                               NaN
274                              NaN                               NaN

     fecha_Asistencia_Recertificacion  fecha_Calif_Recertificacion  \
0                                 NaN                          NaN
1                                 NaN                          NaN
2                                 NaN                          NaN
3                                 NaN                          NaN
4                                 NaN                          NaN
..                                ...                          ...
270                               NaN                          NaN
271                               NaN                          NaN
272                               NaN                          NaN
273                               NaN                          NaN
274                               NaN                          NaN

     fecha_Asistencia_CursoAS_Hlcs_Rezagados  Suma_Refuerzos
0                                        NaN               0
1                                        NaN               0
2                                        NaN               1
3                                        NaN               0
4                                        NaN               0
..                                       ...             ...
270                                      NaN               1
271                                      NaN               0
272                                      NaN               0
273                                      NaN               1
274                                      NaN               0

[275 rows x 17 columns]

In [54]:
# Recertificacion

In [55]:
Recertificacion = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Recertificacion ')

In [56]:
Recertificacion['fecha_Asistencia_Recertificacion2']=1

In [57]:
Recertificacion=Recertificacion[['Selecciona tu nombre', 'fecha_Asistencia_Recertificacion2']]

In [58]:
Recertificacion.rename(columns={"Selecciona tu nombre": "Nombre_Completo"}, inplace=True)

In [59]:
Recertificacion=Recertificacion.drop_duplicates(subset=['Nombre_Completo'])

In [60]:
df_pivot2.insert(1, 'fecha_Asistencia_Recertificacion2', df_pivot2['Nombre_Completo'].map(Recertificacion.set_index('Nombre_Completo')['fecha_Asistencia_Recertificacion2']))
print (df_pivot2)

                        Nombre_Completo  fecha_Asistencia_Recertificacion2  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL                                NaN
1      AGUIAR SANCHEZ DOLORES MARGARITA                                NaN
2         ALEJANDRO PABLO MARIA ARACELI                                NaN
3       ALEMAN CISNEROS MARIA GUADALUPE                                1.0
4            ALMARAZ RUIZ CLAUDIA IVONE                                NaN
..                                  ...                                ...
270             GISELA URBALEJO SANCHEZ                                NaN
271                   Natividad vargas                                 NaN
272         JINEZ CÁRDENAS ROSA CECILIA                                NaN
273       Cesar guadalupe moreno robles                                NaN
274  Carlos Alberto González Rodríguez                                 NaN

     fecha_Asistencia_Ref_CDFNogNayar2  fecha_Asistencia_Ref_BepRicaCol2  \
0                                  NaN                               NaN
1                                  NaN                               NaN
2                                  NaN                               NaN
3                                  NaN                               NaN
4                                  NaN                               NaN
..                                 ...                               ...
270                                NaN                               NaN
271                                NaN                               NaN
272                                NaN                               NaN
273                                NaN                               NaN
274                                NaN                               NaN

     fecha_Asistencia_RefARCA2  fecha_Asistencia_RefFEMSA2  Calificacion  \
0                          NaN                         NaN           NaN
1                          NaN                         NaN           NaN
2                          NaN                         1.0           1.0
3                          1.0                         NaN           NaN
4                          NaN                         NaN           NaN
..                         ...                         ...           ...
270                        NaN                         NaN           1.0
271                        NaN                         NaN           NaN
272                        NaN                         NaN           NaN
273                        1.0                         NaN           NaN
274                        NaN                         NaN           NaN

     fecha_AsistEval_CAPGral_2  fecha_AsistEval_CAPGral  \
0                          NaN                      NaN
1                          NaN                      NaN
2                          1.0                      1.0
3                          NaN                      NaN
4                          NaN                      NaN
..                         ...                      ...
270                        1.0                      1.0
271                        NaN                      NaN
272                        NaN                      NaN
273                        1.0                      NaN
274                        NaN                      NaN

     fecha_AsistEval_EVAGral  fecha_Asistencia_RefFEMSA  \
0                        NaN                        NaN
1                        NaN                        NaN
2                   1.000000                        1.0
3                   0.944444                        NaN
4                        NaN                        NaN
..                       ...                        ...
270                 0.888889                        NaN
271                      NaN                        NaN
272                      NaN                        NaN
273                 0.944444                        NaN
274                 0.833333                        NaN

     fecha_Asistencia_RefARCA  fecha_Asistencia_Ref_BepRicaCol  \
0                         NaN                              NaN
1                         NaN                              NaN
2                         NaN                              NaN
3                         NaN                              NaN
4                         NaN                              NaN
..                        ...                              ...
270                       NaN                              NaN
271                       NaN                              NaN
272                       NaN                              NaN
273                       1.0                              NaN
274                       NaN                              NaN

     fecha_Asistencia_Ref_CDFNogNayar  fecha_Asistencia_Recertificacion  \
0                                 NaN                               NaN
1                                 NaN                               NaN
2                                 NaN                               NaN
3                                 NaN                               NaN
4                                 NaN                               NaN
..                                ...                               ...
270                               1.0                               NaN
271                               NaN                               NaN
272                               NaN                               NaN
273                               NaN                               NaN
274                               NaN                               NaN

     fecha_Calif_Recertificacion  fecha_Asistencia_CursoAS_Hlcs_Rezagados  \
0                            NaN                                      NaN
1                            NaN                                      NaN
2                            NaN                                      NaN
3                            NaN                                      NaN
4                            NaN                                      NaN
..                           ...                                      ...
270                          NaN                                      NaN
271                          NaN                                      NaN
272                          NaN                                      NaN
273                          NaN                                      NaN
274                          NaN                                      NaN

     Suma_Refuerzos
0                 0
1                 0
2                 1
3                 0
4                 0
..              ...
270               1
271               0
272               0
273               1
274               0

[275 rows x 18 columns]

In [61]:
# Recertificación Octubre

In [62]:
EvalOct21_Recertificacion = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Hoja2')

In [63]:
EvalOct21_Recertificacion=EvalOct21_Recertificacion[['Nombre de la persona evaluada', 'Calificacion']]

In [64]:
EvalOct21_Recertificacion.rename(columns={"Nombre de la persona evaluada": "Nombre_Completo"}, inplace=True)

In [65]:
EvalOct21_Recertificacion.rename(columns={"Calificacion": "Calificacion2"}, inplace=True)

In [66]:
EvalOct21_Recertificacion=EvalOct21_Recertificacion.drop_duplicates(subset=['Nombre_Completo'])

In [67]:
df_pivot2.insert(1, 'Calificacion2', df_pivot2['Nombre_Completo'].map(EvalOct21_Recertificacion.set_index('Nombre_Completo')['Calificacion2']))
print (df_pivot2)

                        Nombre_Completo  Calificacion2  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL            NaN
1      AGUIAR SANCHEZ DOLORES MARGARITA            NaN
2         ALEJANDRO PABLO MARIA ARACELI            NaN
3       ALEMAN CISNEROS MARIA GUADALUPE            NaN
4            ALMARAZ RUIZ CLAUDIA IVONE            NaN
..                                  ...            ...
270             GISELA URBALEJO SANCHEZ       0.857143
271                   Natividad vargas             NaN
272         JINEZ CÁRDENAS ROSA CECILIA            NaN
273       Cesar guadalupe moreno robles       0.809524
274  Carlos Alberto González Rodríguez             NaN

     fecha_Asistencia_Recertificacion2  fecha_Asistencia_Ref_CDFNogNayar2  \
0                                  NaN                                NaN
1                                  NaN                                NaN
2                                  NaN                                NaN
3                                  1.0                                NaN
4                                  NaN                                NaN
..                                 ...                                ...
270                                NaN                                NaN
271                                NaN                                NaN
272                                NaN                                NaN
273                                NaN                                NaN
274                                NaN                                NaN

     fecha_Asistencia_Ref_BepRicaCol2  fecha_Asistencia_RefARCA2  \
0                                 NaN                        NaN
1                                 NaN                        NaN
2                                 NaN                        NaN
3                                 NaN                        1.0
4                                 NaN                        NaN
..                                ...                        ...
270                               NaN                        NaN
271                               NaN                        NaN
272                               NaN                        NaN
273                               NaN                        1.0
274                               NaN                        NaN

     fecha_Asistencia_RefFEMSA2  Calificacion  fecha_AsistEval_CAPGral_2  \
0                           NaN           NaN                        NaN
1                           NaN           NaN                        NaN
2                           1.0           1.0                        1.0
3                           NaN           NaN                        NaN
4                           NaN           NaN                        NaN
..                          ...           ...                        ...
270                         NaN           1.0                        1.0
271                         NaN           NaN                        NaN
272                         NaN           NaN                        NaN
273                         NaN           NaN                        1.0
274                         NaN           NaN                        NaN

     fecha_AsistEval_CAPGral  fecha_AsistEval_EVAGral  \
0                        NaN                      NaN
1                        NaN                      NaN
2                        1.0                 1.000000
3                        NaN                 0.944444
4                        NaN                      NaN
..                       ...                      ...
270                      1.0                 0.888889
271                      NaN                      NaN
272                      NaN                      NaN
273                      NaN                 0.944444
274                      NaN                 0.833333

     fecha_Asistencia_RefFEMSA  fecha_Asistencia_RefARCA  \
0                          NaN                       NaN
1                          NaN                       NaN
2                          1.0                       NaN
3                          NaN                       NaN
4                          NaN                       NaN
..                         ...                       ...
270                        NaN                       NaN
271                        NaN                       NaN
272                        NaN                       NaN
273                        NaN                       1.0
274                        NaN                       NaN

     fecha_Asistencia_Ref_BepRicaCol  fecha_Asistencia_Ref_CDFNogNayar  \
0                                NaN                               NaN
1                                NaN                               NaN
2                                NaN                               NaN
3                                NaN                               NaN
4                                NaN                               NaN
..                               ...                               ...
270                              NaN                               1.0
271                              NaN                               NaN
272                              NaN                               NaN
273                              NaN                               NaN
274                              NaN                               NaN

     fecha_Asistencia_Recertificacion  fecha_Calif_Recertificacion  \
0                                 NaN                          NaN
1                                 NaN                          NaN
2                                 NaN                          NaN
3                                 NaN                          NaN
4                                 NaN                          NaN
..                                ...                          ...
270                               NaN                          NaN
271                               NaN                          NaN
272                               NaN                          NaN
273                               NaN                          NaN
274                               NaN                          NaN

     fecha_Asistencia_CursoAS_Hlcs_Rezagados  Suma_Refuerzos
0                                        NaN               0
1                                        NaN               0
2                                        NaN               1
3                                        NaN               0
4                                        NaN               0
..                                       ...             ...
270                                      NaN               1
271                                      NaN               0
272                                      NaN               0
273                                      NaN               1
274                                      NaN               0

[275 rows x 19 columns]

In [68]:
#Curso_AS_Hlcs_rezagados

In [69]:
df_Curso_AS_Hlcs_rezagados = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Curso_AS_Hlcs_rezagados')

In [70]:
df_Curso_AS_Hlcs_rezagados['fecha_Asistencia_CursoAS_Hlcs_Rezagados2']=1

In [71]:
df_Curso_AS_Hlcs_rezagados=df_Curso_AS_Hlcs_rezagados[['Selecciona tu nombre', 'fecha_Asistencia_CursoAS_Hlcs_Rezagados2']]

In [72]:
df_Curso_AS_Hlcs_rezagados.rename(columns={"Selecciona tu nombre": "Nombre_Completo"}, inplace=True)

In [73]:
df_Curso_AS_Hlcs_rezagados=df_Curso_AS_Hlcs_rezagados.drop_duplicates(subset=['Nombre_Completo'])

In [74]:
df_pivot2.insert(1, 'fecha_Asistencia_CursoAS_Hlcs_Rezagados2', df_pivot2['Nombre_Completo'].map(df_Curso_AS_Hlcs_rezagados.set_index('Nombre_Completo')['fecha_Asistencia_CursoAS_Hlcs_Rezagados2']))
print (df_pivot2)

                        Nombre_Completo  \
0       ACOSTA MARTINEZ VICTOR EMMANUEL
1      AGUIAR SANCHEZ DOLORES MARGARITA
2         ALEJANDRO PABLO MARIA ARACELI
3       ALEMAN CISNEROS MARIA GUADALUPE
4            ALMARAZ RUIZ CLAUDIA IVONE
..                                  ...
270             GISELA URBALEJO SANCHEZ
271                   Natividad vargas
272         JINEZ CÁRDENAS ROSA CECILIA
273       Cesar guadalupe moreno robles
274  Carlos Alberto González Rodríguez

     fecha_Asistencia_CursoAS_Hlcs_Rezagados2  Calificacion2  \
0                                         NaN            NaN
1                                         NaN            NaN
2                                         NaN            NaN
3                                         1.0            NaN
4                                         NaN            NaN
..                                        ...            ...
270                                       1.0       0.857143
271                                       NaN            NaN
272                                       NaN            NaN
273                                       1.0       0.809524
274                                       NaN            NaN

     fecha_Asistencia_Recertificacion2  fecha_Asistencia_Ref_CDFNogNayar2  \
0                                  NaN                                NaN
1                                  NaN                                NaN
2                                  NaN                                NaN
3                                  1.0                                NaN
4                                  NaN                                NaN
..                                 ...                                ...
270                                NaN                                NaN
271                                NaN                                NaN
272                                NaN                                NaN
273                                NaN                                NaN
274                                NaN                                NaN

     fecha_Asistencia_Ref_BepRicaCol2  fecha_Asistencia_RefARCA2  \
0                                 NaN                        NaN
1                                 NaN                        NaN
2                                 NaN                        NaN
3                                 NaN                        1.0
4                                 NaN                        NaN
..                                ...                        ...
270                               NaN                        NaN
271                               NaN                        NaN
272                               NaN                        NaN
273                               NaN                        1.0
274                               NaN                        NaN

     fecha_Asistencia_RefFEMSA2  Calificacion  fecha_AsistEval_CAPGral_2  \
0                           NaN           NaN                        NaN
1                           NaN           NaN                        NaN
2                           1.0           1.0                        1.0
3                           NaN           NaN                        NaN
4                           NaN           NaN                        NaN
..                          ...           ...                        ...
270                         NaN           1.0                        1.0
271                         NaN           NaN                        NaN
272                         NaN           NaN                        NaN
273                         NaN           NaN                        1.0
274                         NaN           NaN                        NaN

     fecha_AsistEval_CAPGral  fecha_AsistEval_EVAGral  \
0                        NaN                      NaN
1                        NaN                      NaN
2                        1.0                 1.000000
3                        NaN                 0.944444
4                        NaN                      NaN
..                       ...                      ...
270                      1.0                 0.888889
271                      NaN                      NaN
272                      NaN                      NaN
273                      NaN                 0.944444
274                      NaN                 0.833333

     fecha_Asistencia_RefFEMSA  fecha_Asistencia_RefARCA  \
0                          NaN                       NaN
1                          NaN                       NaN
2                          1.0                       NaN
3                          NaN                       NaN
4                          NaN                       NaN
..                         ...                       ...
270                        NaN                       NaN
271                        NaN                       NaN
272                        NaN                       NaN
273                        NaN                       1.0
274                        NaN                       NaN

     fecha_Asistencia_Ref_BepRicaCol  fecha_Asistencia_Ref_CDFNogNayar  \
0                                NaN                               NaN
1                                NaN                               NaN
2                                NaN                               NaN
3                                NaN                               NaN
4                                NaN                               NaN
..                               ...                               ...
270                              NaN                               1.0
271                              NaN                               NaN
272                              NaN                               NaN
273                              NaN                               NaN
274                              NaN                               NaN

     fecha_Asistencia_Recertificacion  fecha_Calif_Recertificacion  \
0                                 NaN                          NaN
1                                 NaN                          NaN
2                                 NaN                          NaN
3                                 NaN                          NaN
4                                 NaN                          NaN
..                                ...                          ...
270                               NaN                          NaN
271                               NaN                          NaN
272                               NaN                          NaN
273                               NaN                          NaN
274                               NaN                          NaN

     fecha_Asistencia_CursoAS_Hlcs_Rezagados  Suma_Refuerzos
0                                        NaN               0
1                                        NaN               0
2                                        NaN               1
3                                        NaN               0
4                                        NaN               0
..                                       ...             ...
270                                      NaN               1
271                                      NaN               0
272                                      NaN               0
273                                      NaN               1
274                                      NaN               0

[275 rows x 20 columns]

In [75]:
df_pivot2.to_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\df_pivot2_oct21.xlsx", sheet_name='Sheet_name_1', index=False)

In [76]:
df_pivot2=df_pivot2[['Nombre_Completo', 'fecha_AsistEval_CAPGral_2', 'Calificacion', 'fecha_Asistencia_RefFEMSA2', 'fecha_Asistencia_RefARCA2', 'fecha_Asistencia_Ref_BepRicaCol2', 'fecha_Asistencia_Ref_CDFNogNayar2', 'fecha_Asistencia_Recertificacion2', 'Calificacion2', 'fecha_Asistencia_CursoAS_Hlcs_Rezagados2']]

In [77]:
df_pivot2.head()

,Nombre_Completo,fecha_AsistEval_CAPGral_2,Calificacion,fecha_Asistencia_RefFEMSA2,fecha_Asistencia_RefARCA2,fecha_Asistencia_Ref_BepRicaCol2,fecha_Asistencia_Ref_CDFNogNayar2,fecha_Asistencia_Recertificacion2,Calificacion2,fecha_Asistencia_CursoAS_Hlcs_Rezagados2
0,ACOSTA MARTINEZ VICTOR EMMANUEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AGUIAR SANCHEZ DOLORES MARGARITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ALEJANDRO PABLO MARIA ARACELI,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,ALEMAN CISNEROS MARIA GUADALUPE,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0
4,ALMARAZ RUIZ CLAUDIA IVONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
df_pivot2.to_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021_2.xlsx", sheet_name='Sheet_name_1', index=False)

In [79]:
df = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021_2.xlsx", sheet_name='Sheet_name_1')

In [80]:
df.head()

,Nombre_Completo,fecha_AsistEval_CAPGral_2,Calificacion,fecha_Asistencia_RefFEMSA2,fecha_Asistencia_RefARCA2,fecha_Asistencia_Ref_BepRicaCol2,fecha_Asistencia_Ref_CDFNogNayar2,fecha_Asistencia_Recertificacion2,Calificacion2,fecha_Asistencia_CursoAS_Hlcs_Rezagados2,Suma_de_refuerzo
0,ACOSTA MARTINEZ VICTOR EMMANUEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,AGUIAR SANCHEZ DOLORES MARGARITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,ALEJANDRO PABLO MARIA ARACELI,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
3,ALEMAN CISNEROS MARIA GUADALUPE,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,1
4,ALMARAZ RUIZ CLAUDIA IVONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [81]:
df['bool'] = np.where(df['Suma_de_refuerzo']== 0, 0, 1)

In [82]:
df

,Nombre_Completo,fecha_AsistEval_CAPGral_2,Calificacion,fecha_Asistencia_RefFEMSA2,fecha_Asistencia_RefARCA2,fecha_Asistencia_Ref_BepRicaCol2,fecha_Asistencia_Ref_CDFNogNayar2,fecha_Asistencia_Recertificacion2,Calificacion2,fecha_Asistencia_CursoAS_Hlcs_Rezagados2,Suma_de_refuerzo,bool
0,ACOSTA MARTINEZ VICTOR EMMANUEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
1,AGUIAR SANCHEZ DOLORES MARGARITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,ALEJANDRO PABLO MARIA ARACELI,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
3,ALEMAN CISNEROS MARIA GUADALUPE,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,1,1
4,ALMARAZ RUIZ CLAUDIA IVONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
270,GISELA URBALEJO SANCHEZ,1.0,1.0,NaN,NaN,NaN,NaN,NaN,0.857143,1.0,0,0
271,Natividad vargas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
272,JINEZ CÁRDENAS ROSA CECILIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
273,Cesar guadalupe moreno robles,1.0,NaN,NaN,1.0,NaN,NaN,NaN,0.809524,1.0,1,1
274,Carlos Alberto González Rodríguez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

In [83]:
df=df[['Nombre_Completo', 'fecha_AsistEval_CAPGral_2', 'Calificacion', 'fecha_Asistencia_RefFEMSA2', 'fecha_Asistencia_RefARCA2', 'fecha_Asistencia_Ref_BepRicaCol2', 'fecha_Asistencia_Ref_CDFNogNayar2', 'fecha_Asistencia_Recertificacion2', 'Calificacion2', 'fecha_Asistencia_CursoAS_Hlcs_Rezagados2', 'bool']]

In [84]:
df.to_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021_3.xlsx", sheet_name='Sheet_name_1', index=False)

In [85]:
######################## PIVOT 3 ########################################

In [86]:
df_pivot3 = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021.xlsx", sheet_name='Pivot3')

In [87]:
df_pivot3.dtypes

Nombre_Completo     object
Calificacion       float64
dtype: object

In [88]:
df_pivot3['Certificado en CC'] = np.where(df_pivot3['Calificacion']>= 0.85, 'Certificado en CC', '')

In [89]:
df_pivot3.head(50)

                         Nombre_Completo  Calificacion  Certificado en CC
0        ACOSTA MARTINEZ VICTOR EMMANUEL           NaN
1       AGUIAR SANCHEZ DOLORES MARGARITA           NaN
2          ALEJANDRO PABLO MARIA ARACELI          1.00  Certificado en CC
3        ALEMAN CISNEROS MARIA GUADALUPE           NaN
4             ALMARAZ RUIZ CLAUDIA IVONE           NaN
5                 ALVAREZ CARRERA DARVIN           NaN
6         Angulo Cervantes Alicia Aurora           NaN
7           ANTONIO ORDAZ KARINA LIZBETH           NaN
8               ARANDA PEÑA MAYRA PAMELA           NaN
9            ARANO MOLINA JULIO BALTAZAR          1.00  Certificado en CC
10       ARELLANO ESPINOZA MARCO ANTONIO           NaN
11                ARELLANO GONZALEZ RAUL          1.00  Certificado en CC
12            BAEZA ESPINOSA RUBEN DARIO          0.85  Certificado en CC
13      BASULTO CARRILLO MARIA GUADALUPE           NaN
14    Beatriz Arianna Hernández Beltrán            NaN
15            BECERRA REYES MIGUEL ANGEL           NaN
16          BOCANEGRA IBARRA PEDRO UZIEL           NaN
17       BOJORGES AGUILERA PEDRO ANTONIO          0.90  Certificado en CC
18             BRAVO CORTES LUIS ALBERTO          0.95  Certificado en CC
19             BUENO ZAMORA JOSE ANTONIO          0.95  Certificado en CC
20             CAAMAL CUEVAS EDER ISRAEL           NaN
21     CABALLERO POLANCO CINTHIA ROSALIA           NaN
22               CAMARA GIL MIGUEL ANGEL           NaN
23                 CAMARGO MENDOZA MARIO           NaN
24                   CANO TIRADO FABIOLA          1.00  Certificado en CC
25         CARLOS RODRIGUEZ IRMA DOLORES           NaN
26                 CASTRO DIAZ FRANCISCO          1.00  Certificado en CC
27               CELAYA BOJORQUEZ GISSEL          1.00  Certificado en CC
28   CERVANTES CHAVARRIA MARTHA PATRICIA          1.00  Certificado en CC
29                 CERVANTES LOPEZ OSCAR          1.00  Certificado en CC
30          Ceseña Olivas Maria De Jesus           NaN
31            CHAVEZ ARREDONDO JUAN JOSE           NaN
32          Chavez Galeana Arely Jatziry           NaN
33                  CHUC UC JOSE EDUARDO          1.00  Certificado en CC
34          CONSTANTINO PULGARON OSVALDO          1.00  Certificado en CC
35             CORDOVA PACHECO ERNESTINA           NaN
36          CORONA FLORES CARLOS ALBERTO           NaN
37                  CORTES SALGADO EDGAR          1.00  Certificado en CC
38  COSTA RICA ESPINDOLA RICARDO ESTEBAN          0.90  Certificado en CC
39                 COTA MURILLO LIDUBINA           NaN
40  CRESPO MARTINEZ MARIA DE LOS ANGELES          0.95  Certificado en CC
41                    CRUZ GARCIA SERGIO          0.95  Certificado en CC
42            Cruz Martinez Julio Andres           NaN
43                  CRUZ MIRANDA ADRIANA           NaN
44               Cruz Olvera Ana Bertha            NaN
45             CUPUL MASSA BLANCA ESTELA          1.00  Certificado en CC
46        DE LA CERDA CERDA HUGO ALBERTO           NaN
47                  DIAZ PANTOJA EUGENIO          0.85  Certificado en CC
48               DONJUAN GUTIERREZ ERICK          0.85  Certificado en CC
49          Emmanuel Rodríguez Hernández          1.00  Certificado en CC

In [90]:
df_pivot3.to_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021_4.xlsx", sheet_name='Sheet_name_1', index=False)

In [91]:
df = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021_4.xlsx", sheet_name='Sheet_name_1')

In [92]:
df = df.fillna(0)

In [93]:
df.dtypes

Nombre_Completo                       object
Calificacion                         float64
Certificado en CC                     object
fecha_Asistencia_RefFEMSA2           float64
fecha_Asistencia_RefARCA2            float64
fecha_Asistencia_Ref_BepRicaCol2     float64
fecha_Asistencia_Ref_CDFNogNayar2    float64
dtype: object

In [94]:
df['Suma_Asistencia_CC']=df['fecha_Asistencia_RefFEMSA2']+df['fecha_Asistencia_RefARCA2']+df['fecha_Asistencia_Ref_BepRicaCol2']+df['fecha_Asistencia_Ref_CDFNogNayar2']

In [95]:
df.head()

,Nombre_Completo,Calificacion,Certificado en CC,fecha_Asistencia_RefFEMSA2,fecha_Asistencia_RefARCA2,fecha_Asistencia_Ref_BepRicaCol2,fecha_Asistencia_Ref_CDFNogNayar2,Suma_Asistencia_CC
0,ACOSTA MARTINEZ VICTOR EMMANUEL,0.0,0,0.0,0.0,0.0,0.0,0.0
1,AGUIAR SANCHEZ DOLORES MARGARITA,0.0,0,0.0,0.0,0.0,0.0,0.0
2,ALEJANDRO PABLO MARIA ARACELI,1.0,Certificado en CC,1.0,0.0,0.0,0.0,1.0
3,ALEMAN CISNEROS MARIA GUADALUPE,0.0,0,0.0,1.0,0.0,0.0,1.0
4,ALMARAZ RUIZ CLAUDIA IVONE,0.0,0,0.0,0.0,0.0,0.0,0.0

In [96]:
df.dtypes

Nombre_Completo                       object
Calificacion                         float64
Certificado en CC                     object
fecha_Asistencia_RefFEMSA2           float64
fecha_Asistencia_RefARCA2            float64
fecha_Asistencia_Ref_BepRicaCol2     float64
fecha_Asistencia_Ref_CDFNogNayar2    float64
Suma_Asistencia_CC                   float64
dtype: object

In [97]:
df=df[['Suma_Asistencia_CC', 'Calificacion', 'Certificado en CC']]

In [98]:
df.to_excel(r"C:\Users\Lenovo\OneDrive - Storecheck S.A. de C.V\Documentos\Area_Training\Asistencia_Oct_2021_5.xlsx", sheet_name='Sheet_name_1', index=False)